name: PHP

on:
  push:
    paths:
      - 'php/**'

jobs:
  Psalm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Installs composer
      run: |
        cd php;
        composer install --ignore-platform-reqs

    - name: Run Psalm
      run: |
        cd php;
        vendor/bin/psalm.phar --threads=2 --no-cache

 

  PHPUnit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Installs composer
      run: |
        cd php;
        composer install --ignore-platform-reqs

    - name: Configure PHPCS
      run: |
        cd php;
        ./vendor/bin/phpunit --fail-on-warning --fail-on-notice  tests/Unit
